### ISSUE TITLE
State Management of the alert in the forgot password page

### ISSUE THREAD

**Issue by blaze021** [GratisDevs/Gratis_alpha#1]
![image](https://user-images.githubusercontent.com/40628308/98088259-3dcaba80-1ea7-11eb-82f3-375d0213a366.png)

The state is updating after two clicks. 

Pls see to it @tyagivipul629 and @palash0007 .

The following file is ForgotPass.js in the src/react-components

**Comment by tyagivipul629** [comment]
I have fixed the issue. You should read more about `setState` function of React. It is an asynchronous function. So javascript won't wait for it to get finished and will go ahead with the execution of other statements that follow `setState`. That is why even if you call `setState` before the second if condition, the state will contain old value. See in the code how I have resolved the issue.
