### ISSUE TITLE
Routing to login page when clicking on Gratis Logo then to the home.

### ISSUE THREAD

**Issue by blaze021** [GratisDevs/Gratis_alpha#3]
We need to make it so that it redirects to home (if the user is loggedin) .

My suggestion would be wrap the Navbar.Brand tag in Redirect.

**Comment by tyagivipul629** [comment]
It would ultimately redirect to the homepage, after staying on login page for 2 sec. I am trying to optimize it by redirecting it directly to homepage if the user is logged in.

**Comment by chi-afk** [comment]
Don't close it until it's done.

**Comment by chi-afk** [comment]
Closing the issue now. If anything comes up do ping #blaze021 for that. I'll look into it.

**Comment by chi-afk** [comment]
.
