### ISSUE TITLE
Main page ie. Homepage has some alignment problems. Use responsive components not by adding new columns to the row.

### ISSUE THREAD

**Issue by chi-afk** [GratisDevs/Gratis_alpha#4]
![image](https://user-images.githubusercontent.com/84595065/120038826-7d164f80-c021-11eb-94a7-e0f928de29b9.png)

**Comment by chi-afk** [comment]
![image](https://user-images.githubusercontent.com/84595065/120039106-00d03c00-c022-11eb-9832-ed08deffc5b0.png)

**Comment by chi-afk** [comment]
My suggestion would be that we use only container not container-fluid and justify-content: center to align the row elements in center.

**Comment by tyagivipul629** [comment]
I have corrected the bug. The problem was that the sum of column widths was adding upto 11, not 12. So I changed Main to col-md-7. Now it's been resolved.
