### ISSUE TITLE
Problem with new navbar

### ISSUE THREAD

**Issue by tyagivipul629** [GratisDevs/Gratis_alpha#5]
The new navbar looks good but it has problems in the mobile version. It is adding unnecessary horizontal and vertical scrolls to the screen. Please fix it.
![Screenshot from 2021-05-29 12-35-21](https://user-images.githubusercontent.com/42613149/120061370-90a1d480-c07a-11eb-8327-1c99c1d23cc6.png)

**Comment by chi-afk** [comment]
There are no visual screens in range 336*661. You don't change screen sizes on a regular basis.

This problem occurs when there is an overflow. Because the size of li items are large enough to oversize the screen.

**Comment by tyagivipul629** [comment]
Below is the SS of the homepage taken on Redmi 7A. I had to zoom out the screen to remove the scrolls. Please look into it.
![Screenshot_2021-05-29-15-29-48-510_com android chrome](https://user-images.githubusercontent.com/42613149/120066274-87713180-c093-11eb-8e06-4d1cf6dcb8e5.png)
I would be good if you keep the contents of the sidebar in the top navbar itself as was in the previous versions.

**Comment by chi-afk** [comment]
> There are no visual screens in range 336*661. You don't change screen sizes on a regular basis.
> 
> This problem occurs when there is an overflow. Because the size of li items are large enough to oversize the screen.

Didn't I make myself clear in this. Make the li elements smaller that's the only solution.

**Comment by chi-afk** [comment]
Use CSS ffs. I'm helping out Tarun, not making his project.
